import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <h1 className="display">Loft Maker London</h1>
           <Image
              src="/logo.png"
              width={120}
              height={120}
              alt="Picture of the author"
            />
        </header>
        {children}
        <footer >
            <div className="top">
              <div>
                <h3>Contact</h3>
                  <li> Craig Darrach</li>
                  <li>Loftmaker@live.co.uk</li>
                  <li>07736777527</li>
              </div>
              <div>
                <h3>Office hours </h3>
                <ul>
                  <li>Mon -Fri 8:00 - 18:00</li>
                  <li> Sat: 10:00 - 15:00</li>
                  <li> Sunday ClOSED</li>
                </ul>
              </div>
              <div>
                <h3>Loft Maker London</h3>
                <p>High quality, reliable, personal contracting and construction services throughout the London and wider Essex region.</p>
              </div>
            </div>
        </footer>
      </body>
    </html>
  );
}
